### ISSUE TITLE
First Card in CTA is slightly higher than the others

### ISSUE THREAD

**Issue by ptrbtlr** [chingu-voyages/v40-geckos-team-18#85]
**Describe the problem**
1st Card (div) is higher than others after mapping over them.

**Actual behavior**
as above.

**Expected behavior**

**To Reproduce**
1. Go to '/'
2. Scroll down to the cards
3. See error

**Screenshots**
![bug](https://user-images.githubusercontent.com/67752829/188278224-ad4e3d20-d839-4bf8-b104-f2bba5378588.png)

**Your Environment:**
 - Google Chrome on MAC OS
 - Any other software that may impact this issue

**Additional Information**

**Comment by victoriacheng15** [comment]
See #84
